modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/ticticboooom/TwerkItMeal/issues"
[[mods]]
modId="twerkitmeal"
version="${file.jarVersion}"
displayName="TwerkItMeal"
credits="Thanks for TicTicBoom for allowing you to twerk once again" #optional
authors="TicTicBoom (Kyle)"
description='''
'''
